/**
 * Convenience aliases over the generated OpenAPI types.
 *
 * `src/generated/api.ts` mirrors openapi.yaml exactly and is regenerated by `pnpm gen`.
 * Reaching into `components['schemas'][...]` at every call site is unreadable, so the
 * names the application actually uses are defined once, here.
 */

import type { components, operations, paths } from './generated/api';

export type { components, operations, paths };

type Schemas = components['schemas'];

export type ApiStoreApp = Schemas['StoreApp'];
export type ApiRobot = Schemas['Robot'];
export type ApiRobotDetail = Schemas['RobotDetail'];
export type ApiTelemetrySample = Schemas['TelemetrySample'];
export type ApiConfigVersion = Schemas['ConfigVersion'];
export type ApiConfigInput = Schemas['ConfigInput'];
export type ApiField = Schemas['Field'];
export type ApiFieldDetail = Schemas['FieldDetail'];
export type ApiMission = Schemas['Mission'];
export type ApiMissionDetail = Schemas['MissionDetail'];
export type ApiMissionInput = Schemas['MissionInput'];
export type ApiSprayEvent = Schemas['SprayEvent'];
export type ApiScoutRun = Schemas['ScoutRun'];
export type ApiDetection = Schemas['Detection'];
export type ApiDetectionDetail = Schemas['DetectionDetail'];
export type ApiIssue = Schemas['Issue'];
export type ApiInspection = Schemas['Inspection'];
export type ApiAnalyticsOverview = Schemas['AnalyticsOverview'];
export type ApiHotspot = Schemas['Hotspot'];
export type ApiGeoPoint = Schemas['GeoPoint'];
export type ApiProblem = Schemas['Problem'];
export type ApiCommandRefusal = Schemas['CommandRefusal'];

export type ApiSeverity = Schemas['Severity'];
export type ApiSource = Schemas['Source'];
export type ApiMissionStatus = Schemas['MissionStatus'];
export type ApiInspectionStatus = Schemas['InspectionStatus'];

/** The alert sentence on the Analytics overview, or null when nothing needs attention. */
export type ApiAlert = NonNullable<ApiAnalyticsOverview['alert']>;

/** Live badge on a store card, e.g. "14 critical". */
export type ApiAppBadge = NonNullable<ApiStoreApp['badge']>;
