"""Initial schema: organizations, users, robots, fields, store, missions, detections.

Autogenerated from the SQLAlchemy models, then hand-checked. TimescaleDB hypertables,
retention and continuous aggregates are applied separately in 0002.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-25 12:44:46.051065

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    The GiST indexes on the geometry and geography columns are not listed here:
    GeoAlchemy2 creates them as part of create_table for every column declared with
    spatial_index=True, and drop_table removes them again.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_catalog",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("scientific_name", sa.String(length=120), nullable=True),
        sa.Column(
            "issue_type",
            sa.Enum(
                "fungus", "insect", "bacteria", "virus", "nutrient", "abiotic", name="issue_type"
            ),
            nullable=False,
        ),
        sa.Column("what_it_is", sa.Text(), nullable=False),
        sa.Column("what_to_do", sa.Text(), nullable=False),
        sa.Column("action_within_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_catalog")),
        sa.UniqueConstraint("code", name="uq_issue_catalog_code"),
    )
    op.create_index(
        op.f("ix_issue_catalog_created_at"), "issue_catalog", ["created_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_index(
        op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False
    )
    op.create_table(
        "store_apps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("tagline", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("field_ops", "insights", "robot", name="app_category"),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=64), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("flow_position", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("route", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_apps")),
        sa.UniqueConstraint("slug", name="uq_store_apps_slug"),
    )
    op.create_index(op.f("ix_store_apps_created_at"), "store_apps", ["created_at"], unique=False)
    op.create_table(
        "fields",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("crop", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("area_hectares", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_fields_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fields")),
        sa.UniqueConstraint("organization_id", "name", name="uq_fields_organization_id_name"),
    )
    op.create_index(op.f("ix_fields_created_at"), "fields", ["created_at"], unique=False)
    op.create_index(op.f("ix_fields_organization_id"), "fields", ["organization_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.Enum("farmer", "operator", "admin", name="user_role"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "field_rows",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column(
            "path",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("length_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("plant_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("row_number >= 1", name=op.f("ck_field_rows_row_number_positive")),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_field_rows_field_id_fields"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_rows")),
        sa.UniqueConstraint("field_id", "row_number", name="uq_field_rows_field_id_row_number"),
    )
    op.create_index(op.f("ix_field_rows_created_at"), "field_rows", ["created_at"], unique=False)
    op.create_index(op.f("ix_field_rows_field_id"), "field_rows", ["field_id"], unique=False)
    op.create_table(
        "robots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("robot_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("firmware", sa.String(length=32), nullable=True),
        sa.Column("serial", sa.String(length=64), nullable=True),
        sa.Column("online", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=True),
        sa.Column("estop_engaged", sa.Boolean(), nullable=False),
        sa.Column("battery_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("current_field_id", sa.UUID(), nullable=True),
        sa.Column("current_row", sa.Integer(), nullable=True),
        sa.Column("active_config_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "battery_percent IS NULL OR (battery_percent >= 0 AND battery_percent <= 100)",
            name=op.f("ck_robots_battery_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["current_field_id"],
            ["fields.id"],
            name=op.f("fk_robots_current_field_id_fields"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_robots_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robots")),
        sa.UniqueConstraint("robot_id", name="uq_robots_robot_id"),
    )
    op.create_index(op.f("ix_robots_created_at"), "robots", ["created_at"], unique=False)
    op.create_index(op.f("ix_robots_last_seen_at"), "robots", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_robots_organization_id"), "robots", ["organization_id"], unique=False)
    op.create_table(
        "app_installs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["store_apps.id"],
            name=op.f("fk_app_installs_app_id_store_apps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_app_installs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_app_installs_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_installs")),
        sa.UniqueConstraint("app_id", "robot_id", name="uq_app_installs_app_id_robot_id"),
    )
    op.create_index(op.f("ix_app_installs_app_id"), "app_installs", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_app_installs_created_at"), "app_installs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_app_installs_organization_id"), "app_installs", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_app_installs_robot_id"), "app_installs", ["robot_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("robot_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("teleop", "estop", "mission", "sprayer", "config_set", name="command_kind"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "accepted",
                "rejected_auth",
                "rejected_lease",
                "rejected_rate_limit",
                "rejected_safety",
                "failed_publish",
                name="command_outcome",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=120), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_audit_log_robot_id_robots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_outcome_created_at", "audit_log", ["outcome", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_robot_id_created_at", "audit_log", ["robot_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_user_id_created_at", "audit_log", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "control_leases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_control_leases_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_control_leases_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_leases")),
        sa.UniqueConstraint("robot_id", name="uq_control_leases_robot_id"),
    )
    op.create_index(
        op.f("ix_control_leases_created_at"), "control_leases", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_control_leases_expires_at"), "control_leases", ["expires_at"], unique=False
    )
    op.create_table(
        "missions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "mode", sa.Enum("autonomous", "remote_control", name="mission_mode"), nullable=False
        ),
        sa.Column(
            "pattern",
            sa.Enum("snake", "perimeter", "custom", name="mission_pattern"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "paused",
                "completed",
                "failed",
                "cancelled",
                name="mission_status",
            ),
            nullable=False,
        ),
        sa.Column("speed_mps", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("auto_spray", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_travelled_m", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_missions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_missions_field_id_fields"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_missions_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
    )
    op.create_index(op.f("ix_missions_created_at"), "missions", ["created_at"], unique=False)
    op.create_index(op.f("ix_missions_robot_id"), "missions", ["robot_id"], unique=False)
    op.create_index(
        "ix_missions_robot_id_status_created_at",
        "missions",
        ["robot_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "robot_config_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("max_speed_mps", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("detection_sensitivity", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("return_to_base_battery_percent", sa.Integer(), nullable=False),
        sa.Column("camera_fps", sa.Integer(), nullable=False),
        sa.Column("obstacle_stop_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_reason", sa.String(length=255), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "camera_fps BETWEEN 1 AND 60", name=op.f("ck_robot_config_versions_camera_fps_range")
        ),
        sa.CheckConstraint(
            "detection_sensitivity >= 0 AND detection_sensitivity <= 1",
            name=op.f("ck_robot_config_versions_detection_sensitivity_range"),
        ),
        sa.CheckConstraint(
            "max_speed_mps > 0 AND max_speed_mps <= 5",
            name=op.f("ck_robot_config_versions_max_speed_range"),
        ),
        sa.CheckConstraint(
            "return_to_base_battery_percent BETWEEN 5 AND 95",
            name=op.f("ck_robot_config_versions_return_to_base_range"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_robot_config_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_robot_config_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_robot_config_versions_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robot_config_versions")),
        sa.UniqueConstraint(
            "robot_id", "version", name="uq_robot_config_versions_robot_id_version"
        ),
    )
    op.create_index(
        op.f("ix_robot_config_versions_created_at"),
        "robot_config_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_robot_config_versions_robot_id"),
        "robot_config_versions",
        ["robot_id"],
        unique=False,
    )
    op.create_table(
        "sensor_readings",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("sensor", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("readings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.Enum("sim", "robot", "cloud", name="source"), nullable=False),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_sensor_readings_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("time", "robot_id", "sensor", name=op.f("pk_sensor_readings")),
    )
    op.create_index(
        "ix_sensor_readings_robot_id_sensor_time",
        "sensor_readings",
        ["robot_id", "sensor", "time"],
        unique=False,
    )
    op.create_table(
        "telemetry",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("battery_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("battery_time_remaining_s", sa.Integer(), nullable=True),
        sa.Column("battery_voltage_v", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("signal_dbm", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("uptime_s", sa.Integer(), nullable=True),
        sa.Column("speed_mps", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cpu_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("gpu_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("memory_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cpu_temp_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("gpu_temp_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("detection_fps", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("storage_used_gb", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("source", sa.Enum("sim", "robot", "cloud", name="source"), nullable=False),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_telemetry_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("time", "robot_id", name=op.f("pk_telemetry")),
    )
    op.create_index("ix_telemetry_robot_id_time", "telemetry", ["robot_id", "time"], unique=False)
    op.create_table(
        "mission_waypoints",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("heading_deg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_mission_waypoints_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_mission_waypoints_mission_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_waypoints")),
        sa.UniqueConstraint("mission_id", "seq", name="uq_mission_waypoints_mission_id_seq"),
    )
    op.create_index(
        op.f("ix_mission_waypoints_mission_id"), "mission_waypoints", ["mission_id"], unique=False
    )
    op.create_table(
        "scout_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=True),
        sa.Column("mission_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "completed", "aborted", name="scout_run_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plants_scanned", sa.Integer(), nullable=False),
        sa.Column("plants_flagged", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("source", sa.Enum("sim", "robot", "cloud", name="source"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plants_flagged <= plants_scanned", name=op.f("ck_scout_runs_flagged_not_over_scanned")
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_scout_runs_field_id_fields"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_scout_runs_mission_id_missions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_scout_runs_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scout_runs")),
    )
    op.create_index(op.f("ix_scout_runs_created_at"), "scout_runs", ["created_at"], unique=False)
    op.create_index(
        "ix_scout_runs_field_id_started_at", "scout_runs", ["field_id", "started_at"], unique=False
    )
    op.create_index(op.f("ix_scout_runs_robot_id"), "scout_runs", ["robot_id"], unique=False)
    op.create_index(op.f("ix_scout_runs_started_at"), "scout_runs", ["started_at"], unique=False)
    op.create_table(
        "detections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("detection_uid", sa.Uuid(), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("field_id", sa.UUID(), nullable=True),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "severity", sa.Enum("low", "moderate", "critical", name="severity"), nullable=False
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("camera", sa.Enum("left", "right", name="camera_side"), nullable=False),
        sa.Column("bbox_x", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_y", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_w", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_h", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("row", sa.Integer(), nullable=True),
        sa.Column("metres_from_edge", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("image_key", sa.String(length=255), nullable=True),
        sa.Column("crop_key", sa.String(length=255), nullable=True),
        sa.Column("source", sa.Enum("sim", "robot", "cloud", name="source"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bbox_x >= 0 AND bbox_x <= 1 AND bbox_y >= 0 AND bbox_y <= 1 AND bbox_w > 0 AND bbox_w <= 1 AND bbox_h > 0 AND bbox_h <= 1",
            name=op.f("ck_detections_bbox_normalised"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_detections_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_detections_field_id_fields"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue_catalog.id"],
            name=op.f("fk_detections_issue_id_issue_catalog"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_detections_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scout_runs.id"],
            name=op.f("fk_detections_run_id_scout_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detections")),
        sa.UniqueConstraint(
            "robot_id", "detection_uid", name="uq_detections_robot_id_detection_uid"
        ),
    )
    op.create_index(op.f("ix_detections_created_at"), "detections", ["created_at"], unique=False)
    op.create_index(op.f("ix_detections_detected_at"), "detections", ["detected_at"], unique=False)
    op.create_index(op.f("ix_detections_field_id"), "detections", ["field_id"], unique=False)
    op.create_index(
        "ix_detections_field_id_severity_detected_at",
        "detections",
        ["field_id", "severity", "detected_at"],
        unique=False,
    )
    op.create_index(op.f("ix_detections_issue_id"), "detections", ["issue_id"], unique=False)
    op.create_index(op.f("ix_detections_robot_id"), "detections", ["robot_id"], unique=False)
    op.create_index(op.f("ix_detections_row"), "detections", ["row"], unique=False)
    op.create_index(op.f("ix_detections_run_id"), "detections", ["run_id"], unique=False)
    op.create_index(
        "ix_detections_run_id_detected_at", "detections", ["run_id", "detected_at"], unique=False
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("detection_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "false_positive", "treated", name="inspection_status"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name=op.f("fk_inspections_detection_id_detections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_inspections_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
    )
    op.create_index(op.f("ix_inspections_created_at"), "inspections", ["created_at"], unique=False)
    op.create_index(
        "ix_inspections_detection_id_created_at",
        "inspections",
        ["detection_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "spray_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=True),
        sa.Column("field_id", sa.UUID(), nullable=True),
        sa.Column("detection_id", sa.UUID(), nullable=True),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column("sprayed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("flow_lpm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("arc_deg", sa.Integer(), nullable=False),
        sa.Column("nozzle_height_cm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("litres", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("auto", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Enum("sim", "robot", "cloud", name="source"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("arc_deg IN (180, 360)", name=op.f("ck_spray_events_arc_deg_valid")),
        sa.CheckConstraint("litres >= 0", name=op.f("ck_spray_events_litres_non_negative")),
        sa.CheckConstraint(
            "nozzle_height_cm BETWEEN 20 AND 90", name=op.f("ck_spray_events_nozzle_height_range")
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name=op.f("fk_spray_events_detection_id_detections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_spray_events_field_id_fields"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_spray_events_mission_id_missions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
            name=op.f("fk_spray_events_robot_id_robots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
            name=op.f("fk_spray_events_triggered_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spray_events")),
    )
    op.create_index(
        op.f("ix_spray_events_created_at"), "spray_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_spray_events_detection_id"), "spray_events", ["detection_id"], unique=False
    )
    op.create_index(
        op.f("ix_spray_events_mission_id"), "spray_events", ["mission_id"], unique=False
    )
    op.create_index(
        "ix_spray_events_robot_id_sprayed_at",
        "spray_events",
        ["robot_id", "sprayed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_spray_events_robot_id_sprayed_at", table_name="spray_events")
    op.drop_index(op.f("ix_spray_events_mission_id"), table_name="spray_events")
    op.drop_index(op.f("ix_spray_events_detection_id"), table_name="spray_events")
    op.drop_index(op.f("ix_spray_events_created_at"), table_name="spray_events")
    op.drop_table("spray_events")
    op.drop_index("ix_inspections_detection_id_created_at", table_name="inspections")
    op.drop_index(op.f("ix_inspections_created_at"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index("ix_detections_run_id_detected_at", table_name="detections")
    op.drop_index(op.f("ix_detections_run_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_row"), table_name="detections")
    op.drop_index(op.f("ix_detections_robot_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_issue_id"), table_name="detections")
    op.drop_index("ix_detections_field_id_severity_detected_at", table_name="detections")
    op.drop_index(op.f("ix_detections_field_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_detected_at"), table_name="detections")
    op.drop_index(op.f("ix_detections_created_at"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_scout_runs_started_at"), table_name="scout_runs")
    op.drop_index(op.f("ix_scout_runs_robot_id"), table_name="scout_runs")
    op.drop_index("ix_scout_runs_field_id_started_at", table_name="scout_runs")
    op.drop_index(op.f("ix_scout_runs_created_at"), table_name="scout_runs")
    op.drop_table("scout_runs")
    op.drop_index(op.f("ix_mission_waypoints_mission_id"), table_name="mission_waypoints")
    op.drop_table("mission_waypoints")
    op.drop_index("ix_telemetry_robot_id_time", table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index("ix_sensor_readings_robot_id_sensor_time", table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index(op.f("ix_robot_config_versions_robot_id"), table_name="robot_config_versions")
    op.drop_index(op.f("ix_robot_config_versions_created_at"), table_name="robot_config_versions")
    op.drop_table("robot_config_versions")
    op.drop_index("ix_missions_robot_id_status_created_at", table_name="missions")
    op.drop_index(op.f("ix_missions_robot_id"), table_name="missions")
    op.drop_index(op.f("ix_missions_created_at"), table_name="missions")
    op.drop_table("missions")
    op.drop_index(op.f("ix_control_leases_expires_at"), table_name="control_leases")
    op.drop_index(op.f("ix_control_leases_created_at"), table_name="control_leases")
    op.drop_table("control_leases")
    op.drop_index("ix_audit_log_user_id_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_robot_id_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_outcome_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_app_installs_robot_id"), table_name="app_installs")
    op.drop_index(op.f("ix_app_installs_organization_id"), table_name="app_installs")
    op.drop_index(op.f("ix_app_installs_created_at"), table_name="app_installs")
    op.drop_index(op.f("ix_app_installs_app_id"), table_name="app_installs")
    op.drop_table("app_installs")
    op.drop_index(op.f("ix_robots_organization_id"), table_name="robots")
    op.drop_index(op.f("ix_robots_last_seen_at"), table_name="robots")
    op.drop_index(op.f("ix_robots_created_at"), table_name="robots")
    op.drop_table("robots")
    op.drop_index(op.f("ix_field_rows_field_id"), table_name="field_rows")
    op.drop_index(op.f("ix_field_rows_created_at"), table_name="field_rows")
    op.drop_table("field_rows")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_fields_organization_id"), table_name="fields")
    op.drop_index(op.f("ix_fields_created_at"), table_name="fields")
    op.drop_table("fields")
    op.drop_index(op.f("ix_store_apps_created_at"), table_name="store_apps")
    op.drop_table("store_apps")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_issue_catalog_created_at"), table_name="issue_catalog")
    op.drop_table("issue_catalog")
    # ### end Alembic commands ###
